import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Header, Menu } from 'src/components/ui'
import { cn } from 'src/lib/utils/cn'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={cn(
                'flex overflow-hidden',
                inter.className
            )}>
                <Menu />
                
                <div className='w-full'>
                    <Header />
                    <div className='w-full h-screen p-4 overflow-auto bg-indigo-50 bg-opacity-50'>
                        {children}
                    </div>
                </div>
            </body>
        </html>
    )
}
